apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345"
        - name: MYSQL_DATABASE
          value: "testemed"
        livenessProbe:
          exec:
            command:
              - mysqladmin
              - ping
              - "-h"
              - "localhost"
              - "-u"
              - "root"
              - "-p12345"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3